name: flutter_country_picker
description: A new flutter plugin project.
version: 0.0.1
author: Alessandro Biessek <alessandro@biessek.rocks>
homepage: https://github.com/biessek/flutter_country_picker

environment:
  sdk: ">=1.19.0  <=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  diacritic: "^0.0.2"
flutter:
  plugin:
    androidPackage: rocks.biessek.fluttercountrypicker
    pluginClass: FlutterCountryPickerPlugin
  assets:
    - assets/flags/
